'packages/backend':
- packages/backend/**/*

'packages/backend:test':
- packages/backend/test/**/*

'packages/frontend':
- packages/frontend/**/*

'packages/frontend:test':
- cypress/**/*

'packages/sw':
- packages/sw/**/*

'packages/comduck-js':
- packages/comduck-js/**/*

'packages/comduck-js:test':
- packages/comduck-js/test/**/*
- packages/comduck-js/test-d/**/*
