apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comduck.fullname" . }}
  labels:
    {{- include "comduck.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "comduck.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "comduck.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: comduck
          image: {{ .Values.image }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ include "comduck.fullname" . }}-configuration
              mountPath: /comduck/.config
              readOnly: true
          ports:
            - containerPort: 3000
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_USER
              value: "example-comduck-user"
            - name: POSTGRES_PASSWORD
              value: "example-comduck-pass"
            - name: POSTGRES_DB
              value: "comduck"
          ports:
            - containerPort: 5432
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
      volumes:
        - name: {{ include "comduck.fullname" . }}-configuration
          configMap:
            name: {{ include "comduck.fullname" . }}-configuration
