name: API report (comduck.js)

on: [push, pull_request]

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm --filter comduck-js build

      - name: Check files
        run: ls packages/comduck-js/built

      - name: API report
        run: pnpm --filter comduck-js api-prod

      - name: Show report
        if: always()
        run: cat packages/comduck-js/temp/comduck-js.api.md
